### ISSUE TITLE
check before get

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/Silimatics#1]
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=sand, clazz=class wiresegal.silimatics.common.item.EnumSandType, values=[dull, rashid, bright, heat, storm, void, trail, blood, pain, sun]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}

**Comment by Eladkay** [comment]
Stacktrace?

**Comment by yrsegal** [comment]
Don't need it i know what this is

**Comment by yrsegal** [comment]
this will be solved when #5 is

**Comment by Eladkay** [comment]
So never
