### ISSUE TITLE
net/minecraft/client/renderer/entity/RenderPlayer

### ISSUE THREAD

**Issue by Telemain** [yrsegal/Silimatics#11]
Having an error with my server on start

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Silimatics (smedry)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/RenderPlayer`

[Full crash report](https://gist.github.com/Telemain/ffaac62cac4bb01375d3ac6ff9c22361)

**Comment by Eladkay** [comment]
Did you build it from source?

**Comment by Schadrach** [comment]
I'm getting the same error, using current version from curse.

**Comment by Telemain** [comment]
I got mine from curse as well

**Comment by Telemain** [comment]
I don't know if this helps, but the problem appears to be isolated to Silimatics 1.2.1 because I downgraded to Silimatics 1.2 and the crash went away

**Comment by Telemain** [comment]
Actually, I just noticed that when downloading "Silimatics 1.2.1" from curse I actually get a file named "Silimatics-r1.1.2" which seems odd

**Comment by yrsegal** [comment]
my *stars* elad, come on

**Comment by NullMagic** [comment]
Just thought you might like to know, this is still an issue. The 1.2.1 file still has 1.1.2 as the file it's passing out.

Edit: I thought I should clarify, in case that is actually the correct file and has just been mislabeled. The crash is still occurring with the latest file from curse.
