### ISSUE TITLE
Use Shadowfacts' Forgelin instead of manually shading Kotlin

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [yrsegal/Silimatics#6]
I'm sure you are already aware of Forgelin, but here's why I think you should use it.

Forgelin shades the Kotlin stdlib and reflection lib so you don't have to. This way, all mods that use Kotlin can just depend on a unified library instead of shading their own copies of the Kotlin libraries. Silimatics using Forgelin would really benefit mods written in Kotlin as a whole.

Forgelin also adds an FML Language Adapter so you can create your @ Mod as an object instead of a class.

It is really easy to add. Here is how it is added in Literal Ascension.

* [Maven repository (line 57-60)](https://bitbucket.org/jamieswhiteshirt/literal-ascension/src/f4789cb15615c4229903ae4826cee6625fe306d4/build.gradle?at=master&fileviewer=file-view-default#build.gradle-57)
* [Dependency (line 65)](https://bitbucket.org/jamieswhiteshirt/literal-ascension/src/f4789cb15615c4229903ae4826cee6625fe306d4/build.gradle?at=master&fileviewer=file-view-default#build.gradle-65)
* [FML Language Adapter (line 18)](https://bitbucket.org/jamieswhiteshirt/literal-ascension/src/f4789cb15615c4229903ae4826cee6625fe306d4/src/main/kotlin/com/jamieswhiteshirt/literalascension/LiteralAscension.kt?at=master&fileviewer=file-view-default#LiteralAscension.kt-18)

Shadowfacts' Forgelin is NOT deprecated by the way. The decision of merging it with ShadowMC is currently being reversed.

**Comment by Eladkay** [comment]
Funny that you mention Forgelin, I actually looked at it this morning and me and wire also took a look at it during TMT. It's a good idea in theory but I think wire said it doesn't matter too much. Would you mind it if we merge it into our lib mod, LibrarianLib?

**Comment by JamiesWhiteShirt** [comment]
I believe merging Forgelin into LibrarianLib eliminates the point of Forgelin. 

Ideally, Silimatics, Literal Ascension and all of Shadowfacts' mods should all depend on Forgelin to avoid compatibility issues with shading and bloated distributions.

**Comment by yrsegal** [comment]
If librarianlib depends on forgelin, this would be fine

**Comment by Eladkay** [comment]
Wire? You decide

**Comment by yrsegal** [comment]
Did I not just decide

**Comment by Eladkay** [comment]
Don't think so

**Comment by Eladkay** [comment]
But if your decision was "accept" I'll do it tomorrow and close this from a commit

**Comment by JamiesWhiteShirt** [comment]
Will you be doing this for LibrarianLib and other mods too?

**Comment by yrsegal** [comment]
LibrarianLib is what our mods depend on, so yeah, all our mods that depend on it will by extension be forgelin.

**Comment by Eladkay** [comment]
@yrsegal I don't see a need for that as Silimatics is the only kotlin actual content mod that is dependent on liblib. But if you still want to make liblib depend on forgelin, I'm not a liblib dev anymore so you can have a good time with that

**Comment by Eladkay** [comment]
Done a looooong time ago now
