### ISSUE TITLE
Crash on Load 

### ISSUE THREAD

**Issue by ChloeDawn** [yrsegal/Silimatics#7]
Game crashes during start up.

**Mod version:** [1.2](https://minecraft.curseforge.com/projects/silimatics/files/2383335)
**Forge version:** [1.10.2-12.18.3.2221](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2221/forge-1.10.2-12.18.3.2221-changelog.txt)

**Crash report:** [crash-2017-02-18_19.35.06-client.txt](https://gist.github.com/InsomniaKitten/eca24a9a33c47839c5cea3788ea86f5c)

**Comment by Eladkay** [comment]
settled
